name: poly_bool_dart
description: Boolean operations on polygons (union, intersection, difference, xor) (this library is a port for flutter of polybooljs.
version: 0.1.0
homepage: https://github.com/mohammedX6/poly_bool_dart/tree/master


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_jts: ^0.2.1
  quiver: ^3.0.1+1
  latlong2: ^0.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

